#++++++++++++++++++++++++++++++++++++++
# PHP application Docker container
#++++++++++++++++++++++++++++++++++++++

FROM php:7.2.5-fpm

# Copy custom php.ini
COPY ./php.ini /usr/local/etc/php/conf.d/php.ini

# Set Volumes
VOLUME ["/var/www", "/usr/local/etc"]

# Configure volume/workdir
WORKDIR /var/www/


