version: '3.7'

services:

  phpapp:
    build:
      context: ./etc/php/
      dockerfile: Dockerfile
    container_name: docker-phpapp.local-app
    restart: always
    cap_add:
      - CAP_SYS_PTRACE
    privileged: true
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/php.dev.ini:/usr/local/etc/php/conf.d/php.dev.ini
      - ./etc/logs/xdebug.log:/tmp/xdebug.log
      - ./etc/logs/debug:/tmp/debug
      - ./app:/var/www
      - ./resources:/var/resources
    env_file:
      - ./etc/php/.env
      - ./etc/php/dev.env
#    expose:
#      - 6778
    entrypoint: /var/www/bootstrap.sh
#    environment:
#      VIRTUAL_HOST: docker-phpapp.local
#      VIRTUAL_PORT: 6778

networks:
  default:
    external:
      name: nginx-proxy
