version: '3'

services:

  web:
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile.development
    container_name: docker-example.local-web
    ports:
      - 8000:80
      - 3000:443
    restart: always
    volumes:
      - ./etc/ssl:/etc/ssl
      - ./app:/var/www
    # cap and privileged needed for slowlog
    cap_add:
      - CAP_SYS_PTRACE
    privileged: true
    environment:
      VIRTUAL_HOST: docker-example.local
      VIRTUAL_PORT: 80
    links:
      - app
    depends_on:
      - app

  app:
    build:
      context: ./etc/php/
      dockerfile: Dockerfile.development
    container_name: docker-example.local-app
    restart: always
    volumes:
      - ./app:/var/www
    env_file:
      - ./etc/.env

networks:
  default:
    external:
      name: nginx-proxy